version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - ./tmp/redis:/data
  web:
    stdin_open: true
    tty: true
    build: .
    volumes:
      - .:/d2live
    command: bundle exec puma -C config/puma.rb
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
  sidekiq:
    stdin_open: true
    tty: true
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - db
      - redis
    volumes:
      - '.:/d2live'
