version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - ./tmp/redis:/data
  web:
    build: .
    volumes:
      - .:/d2live
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
  sidekiq:
    build: .
    depends_on:
      - db
      - redis
    command: bundle exec sidekiq
    volumes:
      - '.:/d2live'
